.pc
.TH "ArcamClient" 1 "2020-08-30" "0.0.0" "ArcamClient Manual"

.SH NAME
arcamclient \- a GTK+3 GUI for controlling an Arcam amp over Ethernet.

.SH SYNOPSIS
.B arcamclient

.SH DESCRIPTION
ArcamClient is a GTK+ desktop application for controlling an Arcam amplifier over Ethernet.

.SH AUTHOR
Russel Winder (2020–) <russel@winder.org.uk>

.SH COPYRIGHT
Copyright © 2020  Russel Winder <russel@winder.org.uk>
